CREATE TABLE IF NOT EXISTS events (
  seq INTEGER PRIMARY KEY,
  ts_ms INTEGER NOT NULL,
  kind INTEGER NOT NULL,
  qso_id INTEGER,
  payload BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS snapshots (
  id INTEGER PRIMARY KEY,
  last_seq INTEGER NOT NULL,
  ts_ms INTEGER NOT NULL,
  payload BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
